CREATE TABLE images
  ( id SERIAL8 PRIMARY KEY UNIQUE
  , user_id SERIAL8 NOT NULL REFERENCES users (id) ON DELETE CASCADE
  , title VARCHAR(100) NOT NULL
  , file_path VARCHAR(100) NOT NULL
  , created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
  , updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);
