CREATE TABLE mailing_list
  ( id SERIAL8 PRIMARY KEY UNIQUE
  , email VARCHAR UNIQUE
  , created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
  , updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);
