CREATE TABLE users
  ( id SERIAL8 PRIMARY KEY UNIQUE
  , email VARCHAR NOT NULL UNIQUE
  , password VARCHAR NOT NULL
  , created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
  , updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);