CREATE TABLE blog_posts
  ( id SERIAL8 PRIMARY KEY UNIQUE
  , author_id SERIAL8 NOT NULL REFERENCES users (id) ON DELETE RESTRICT
  , title VARCHAR NOT NULL
  , content VARCHAR NOT NULL
  , published BOOLEAN NOT NULL DEFAULT False
  , hero_image_id INTEGER NULL REFERENCES images(id) ON DELETE SET NULL
  , created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
  , updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE blog_comments
  ( id SERIAL8 PRIMARY KEY UNIQUE
  , post_id SERIAL8 NOT NULL REFERENCES blog_posts (id)
  , author_id SERIAL8 NOT NULL REFERENCES users (id) ON DELETE CASCADE
  , content VARCHAR NOT NULL
  , created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
  , updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);
